"""empty message

Revision ID: 3a33261273ee
Revises: c25f5f7238ba
Create Date: 2022-08-13 18:07:12.524957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a33261273ee'
down_revision = 'c25f5f7238ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'date_created')
    op.drop_column('Artist', 'date_created')
    # ### end Alembic commands ###
